;/*FB_PKG_DELIM*/

__d("PolarisClipsHomeRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"6902412236487816",metadata:{},name:"PolarisClipsHomeRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisDirectInboxQPInterstitialQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"7495362107146916",metadata:{},name:"PolarisDirectInboxQPInterstitialQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisActivityFeedRoot.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{}}},root:c("JSResourceForInteraction")("PolarisActivityFeedRoot.react").__setRef("PolarisActivityFeedRoot.entrypoint")};g["default"]=a}),98);
__d("react-relay/relay-hooks/NestedRelayEntryPointBuilderUtils",[],(function(a,b,c,d,e,f){"use strict";function a(a){return a}f.NestedRelayEntryPoint=a}),66);
__d("NestedRelayEntryPointBuilderUtils",["react-relay/relay-hooks/NestedRelayEntryPointBuilderUtils"],(function(a,b,c,d,e,f){"use strict";Object.keys(importNamespace("react-relay/relay-hooks/NestedRelayEntryPointBuilderUtils")).forEach(function(a){if(a==="default"||a==="__esModule")return;f[a]=importNamespace("react-relay/relay-hooks/NestedRelayEntryPointBuilderUtils")[a]})}),null);
__d("PolarisClipsViewerDefaultContent.entrypoint",["JSResourceForInteraction","PolarisClipsHomeRootQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var b={container_module:"clips_tab_desktop_page"};a.routeProps.media_id!=null&&(b=babelHelpers["extends"]({},b,{chaining_media_id:a.routeProps.media_id,should_refetch_chaining_media:!0}));return{queries:{polarisClipsTabRootQuery:{options:{},parameters:c("PolarisClipsHomeRootQuery$Parameters"),variables:{data:b}}}}},root:c("JSResourceForInteraction")("PolarisClipsViewerDefaultContainer.react").__setRef("PolarisClipsViewerDefaultContent.entrypoint")};b=a;g["default"]=b}),98);
__d("PolarisClipsTabRoot.entrypoint",["JSResourceForInteraction","NestedRelayEntryPointBuilderUtils","PolarisClipsViewerDefaultContent.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{entryPoints:{containerContent:h(a)},queries:{}}},root:c("JSResourceForInteraction")("PolarisClipsTabRoot.react").__setRef("PolarisClipsTabRoot.entrypoint")};function h(a){return d("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:b("PolarisClipsViewerDefaultContent.entrypoint"),entryPointParams:a})}g["default"]=a}),98);
__d("PolarisDirectInboxMobileRoot.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{}}},root:c("JSResourceForInteraction")("PolarisDirectInboxMobileRoot.react").__setRef("PolarisDirectInboxMobileRoot.entrypoint")};g["default"]=a}),98);
__d("PolarisDirectInboxRoot.entrypoint",["JSResourceForInteraction","PolarisDirectInboxQPInterstitialQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{qpInterstitialQueryRef:{parameters:c("PolarisDirectInboxQPInterstitialQuery$Parameters"),variables:{}}}}},root:c("JSResourceForInteraction")("PolarisDirectInboxRoot.react").__setRef("PolarisDirectInboxRoot.entrypoint")};g["default"]=a}),98);
__d("PolarisExploreRoot.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{}}},root:c("JSResourceForInteraction")("PolarisExploreRoot.react").__setRef("PolarisExploreRoot.entrypoint")};g["default"]=a}),98);